### PR TITLE
Add restart recomend and user theme extension

### PR DESCRIPTION
**Pull request by ahoneybun**

### CODE REVIEW

**Comment by isantop** [comment]
I don't think it's necessary to mention the User-Themes extension in the Readme; there is already a note about it in GNOME Tweak tool when the theme is applied, and this is standard-issue for any GNOME theme. Restarting the whole computer is also unneeded. Instead, simply restarting the shell and any open applications is generally enough.

**Comment by ahoneybun** [comment]
Want me to tweak it to just have the restart the shell ? Alt+F2 and r ?

**Comment by isantop** [comment]
That might work. I just want to avoid documentation overload

**Comment by ryanleesipes** [comment]
@ahoneybun you adding that?

**Comment by ahoneybun** [comment]
Yea @ryanleesipes sorry lost track of time there.

**Pull request merged**
